name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          
  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master